version: '3.8'
services:
  db1:
    image: postgres:14-alpine
    container_name: userDb
    ports:
      - '15001:5432'
    restart: 'no'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret99
    volumes:
      - db:/var/lib/postgresql/data
  db2:
    image: postgres:14-alpine
    container_name: catalogueDb
    ports:
      - '15002:5432'
    restart: 'no'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret99
    volumes:
      - db:/var/lib/postgresql/data
  db3:
    image: postgres:14-alpine
    container_name: orderDb
    ports:
      - '15003:5432'
    restart: 'no'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret99
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
